# Generated by Django 3.2 on 2022-04-27 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_auto_20220427_1207'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wishlist',
        ),
    ]
