# Generated by Django 3.2 on 2022-04-27 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_delete_wishlist'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartorder',
            options={'verbose_name_plural': '3. Orders'},
        ),
        migrations.AlterModelOptions(
            name='cartorderitems',
            options={'verbose_name_plural': '4. Order Items'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': '1. Categories'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name_plural': '2. Products'},
        ),
    ]
